version: '3'

networks:
  default:
    external:
      name: monitoring_network

services:

  aspnetcoreapp:
    image: aspnetcoreapp
    build:
      context: ./aspnetcoreapp
    ports:
      - "5000:5000"
    depends_on:
      - 'influxdb'

  influxdb:
    build: influxdb
    container_name: influxdb
    env_file:
      - influxdb.env
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - ./data/grafana_data:/var/lib/grafana
